### ISSUE TITLE
[Chore] No CI on pull requests — tests never run before merge

### ISSUE THREAD

**Issue by luketmoss** [luketmoss/hive#247]
## Summary

Add a `ci.yml` GitHub Actions workflow that runs both test suites, the frontend typecheck and build, and an Apps Script typecheck on every pull request and on every push to `main` — and fix `apps-script/tsconfig.json` so the `.ts` files under `apps-script/tests/` are actually covered.

Deferred from #241 — found while reviewing PR #245.

## Context

`.github/workflows/` contains only `deploy.yml`, which triggers on `push` to `main` (paths `frontend/**`) and `workflow_dispatch`. Nothing triggers on `pull_request`, so `gh pr view <N> --json statusCheckRollup` returns `[]` for every PR this repo has ever had.

The pipeline treats a green check as a gate (`/review` step 5 confirms CI before approving, `/ship` refuses on failing or absent checks), but there is nothing to be green or red. This is the direct cause of #246, where 6 frontend tests sat red on `main` across two merges with nothing surfacing it.

Second-order gap: `apps-script/tsconfig.json` has `include: ["src/**/*.ts"]` and `apps-script/src/` is all `.js` by design, so that pattern matches zero files (`TS18003`) while the real `.ts` files — `apps-script/tests/*.test.ts` and `apps-script/vitest.config.ts` — are typechecked by nothing.

`main` is green as of c85cfe3 (#249 fixed #246), so the new workflow will not land red.

### AC1: CI runs on every pull request
- **Given** `.github/workflows/ci.yml` exists on `main`
- **When** a pull request is opened or updated against `main`
- **Then** a workflow run named `CI` appears on that PR, and `gh pr view <N> --json statusCheckRollup` returns a non-empty array naming its jobs

### AC2: Both suites, the typecheck and the build all gate the PR
- **Given** a CI run triggered by a pull request
- **When** the run completes
- **Then** it has executed `npm ci` + `npm test` + `npx tsc --noEmit` + `npm run build` in `frontend/`, and `npm ci` + `npm test` + a TypeScript typecheck in `apps-script/`
- **And** the frontend and apps-script work run as two separate jobs, so a failure names which side broke

### AC3: A failing test turns the check red
- **Given** the CI workflow on a branch
- **When** any of those steps exits non-zero (e.g. a deliberately broken assertion in either suite)
- **Then** the workflow conclusion is `failure` and the PR's check rollup is not green

### AC4: A bad merge to main is still visible
- **Given** a commit lands on `main` (via merge or directly)
- **When** CI runs for that push
- **Then** the same jobs run against `main`, so a merge that bypassed a PR still produces a red check on the branch

### AC5: apps-script typecheck covers the test files
- **Given** `apps-script/tsconfig.json`
- **When** `npm run typecheck` is run in `apps-script/`
- **Then** it exits 0 with no `TS18003: No inputs were found` error
- **And** introducing a type error in `apps-script/tests/*.test.ts` makes it exit non-zero

### AC6: Deployment is unaffected
- **Given** `.github/workflows/deploy.yml`
- **When** a commit lands on `main` touching `frontend/**`
- **Then** the Pages deploy runs exactly as before — `deploy.yml` is not modified by this issue, and CI runs alongside it, not in place of it

### In Scope
- New `.github/workflows/ci.yml` with `pull_request` (targeting `main`) and `push` to `main` triggers, plus `workflow_dispatch`
- Two jobs: `frontend` and `apps-script`, both on `ubuntu-latest`, Node 20 with npm cache, matching `deploy.yml`'s setup step
- `npm run typecheck` script added to `apps-script/package.json`
- `apps-script/tsconfig.json` `include` widened to cover `tests/**/*.ts` (and `vitest.config.ts`) alongside `src`
- `permissions: contents: read` only — CI needs nothing else

### Out of Scope
- **Branch protection / required status checks.** That is a repo-settings change outside the repo tree, and `/ship` already refuses to merge on a failing check. Making the check *required* can follow once the workflow has a few green runs behind it.
- Any change to `deploy.yml`
- Coverage reporting, lint, matrix builds across Node versions, caching beyond `setup-node`'s npm cache
- Path filters on the CI workflow — a check that silently skips cannot serve as a gate

## Technical Notes
- **Files:** `.github/workflows/ci.yml` (new), `apps-script/tsconfig.json`, `apps-script/package.json`
- **Complexity:** small
- **Rules sync required:** no — this touches no business rules on either side
- Node 20 + `cache: npm` with `cache-dependency-path` per job, mirroring `deploy.yml`. Both `frontend/` and `apps-script/` have a `package-lock.json`, so `npm ci` works in each.
- The frontend `build` step passes `VITE_GOOGLE_CLIENT_ID` / `VITE_SPREADSHEET_ID` from secrets for parity with `deploy.yml`; the build does not fail without them, so it also works on a fork.
- `frontend`'s `npm run build` already runs `tsc --noEmit` as its first half, but the typecheck stays an explicit step so a type error is attributable on its own line.
- `apps-script` tests import `vitest` explicitly and `tsconfig` pins `types: ["google-apps-script"]`; if widening `include` surfaces missing vitest globals, add `"vitest/globals"` to `types` rather than loosening `strict`.

## Open Questions
None. Both questions from the original write-up are answered above: the check is advisory for now (branch protection out of scope), and Node is pinned to 20 to match `deploy.yml`.

---

## Results

Shipped as PR #250. Three files, 58 insertions, no production code touched.

**What landed:** `.github/workflows/ci.yml` with two parallel `ubuntu-latest` jobs — `Frontend (test, typecheck, build)` running `npm ci` → `npm test` → `npx tsc --noEmit` → `npm run build`, and `Apps Script (test, typecheck)` running `npm ci` → `npm test` → `npm run typecheck`. Triggers: `pull_request` targeting `main`, `push` to `main`, `workflow_dispatch`. No path filters. `permissions: contents: read` only. Plus `apps-script/tsconfig.json` `include` widened to `["src/**/*.ts", "tests/**/*.ts", "vitest.config.ts"]` and a new `typecheck` script.

**The chicken-and-egg didn't bite.** The open worry going in was that the PR introducing CI might be the one PR that can't have a check. It isn't: `pull_request` workflows are read from the PR branch's own copy of the workflow file, so #250 got both jobs on its first push. #250 is the first PR in this repo's history with a non-empty `statusCheckRollup`, and it was green on the commit that merged.

**AC3 was proved, not assumed.** Rather than reasoning that a failing test would turn the check red, a deliberate `expect(1).toBe(2)` was pushed as `db54fec`. The apps-script job went `FAILURE` while the frontend job stayed `SUCCESS` — which incidentally proved AC2's attribution requirement too, since the red check named which side broke. Reverted in `493f5a3`, and `git diff main --stat` confirmed the net diff was back to exactly the 3 intended files. That round trip cost about four minutes and is the only reason "CI is green" now means something here.

**The tsconfig bug was worse than a config nit.** `include: ["src/**/*.ts"]` against an all-`.js` `src/` matched zero files, so `tsc` didn't typecheck-and-pass — it aborted with `TS18003` before checking anything. The `.ts` test files had never been typechecked at all. Verified both directions: exit 0 after the fix, and a seeded `const x: number = "str"` in `tests/rules.test.ts` now produces `TS2322` and exit 2.

**What `/pm` decided that could have gone the other way:** the check is advisory, not required. Branch protection is a repo-settings change outside the tree, and `/ship` already refuses to merge on a failing check, so the gate holds without it. Worth revisiting once this workflow has a few green runs behind it — that is the step that would make the gate un-bypassable rather than merely present.

**What `/review` flagged without blocking:** `cancel-in-progress: true` applies to the `main` group as well as PR groups, so two merges landing within a couple of minutes would cancel the earlier `main` run and leave that intermediate commit without a verdict. The newest `main` commit always gets a full run, so this is a refinement, not a defect; `cancel-in-progress: ${{ github.event_name == 'pull_request' }}` is the fix if it ever matters. Also noted: the frontend typecheck is nominally duplicated inside `npm run build`, kept separate deliberately so a type error gets its own attributable failure line.

**Security posture of the workflow, checked explicitly:** uses `pull_request` and not `pull_request_target`, and interpolates no `${{ github.event.* }}` value into any `run:` block — the two standard Actions injection and privilege-escalation vectors are both absent by construction.

**No UI verification, and no pretending otherwise.** Demo mode was not run and the 375px / dark-theme matrix was not exercised, because this issue changes only CI configuration and TypeScript project setup. There is no user-facing surface here.

**What this unblocks:** #241/PR #245, #243, #239, #242 and #240 can now each get a real green check before merging, which was the entire point. #246 was the warning shot — six frontend tests sat red on `main` across two merges with nothing to surface them. That specific failure mode is now closed.

**Deferred:** nothing. No out-of-scope work was found that warranted its own issue.

**Comment by luketmoss** [comment]
PM refinement complete — 6 ACs, scope and technical notes written into the issue body.

`/ux` skipped: this issue changes only `.github/workflows/`, `apps-script/tsconfig.json` and `apps-script/package.json`. There is no user-facing surface, so there is nothing for a UX audit to inspect.

Both original open questions are resolved in-spec rather than halting:
- **Required vs advisory check** — advisory. Branch protection is a repo-settings change outside the repo tree, and `/ship` already refuses to merge on a failing check. Marked out of scope, revisitable once the workflow has green runs behind it.
- **Node version** — pinned to 20, matching `deploy.yml`'s existing setup step.

Moving to Refined.

**Comment by luketmoss** [comment]
## QA Report — Issue #247

### Automated: Frontend ✓ · TypeScript ✓ · Apps Script ✓
Local on the branch head: frontend 1163 passed (61 files), `tsc --noEmit` clean, `npm run build` clean; apps-script 23 passed, `npm run typecheck` exit 0. The same suites also ran in GitHub Actions on this PR.

### AC Results

#### AC1: CI runs on every pull request — PASS
The workflow ran on this very PR. `gh pr view 250 --json statusCheckRollup` returns a non-empty array naming both jobs, where the same query on #245 and #238 returns `[]`. Confirmed on `pull_request` event via `gh run list --workflow=ci.yml`.

#### AC2: Both suites, the typecheck and the build all gate the PR — PASS
Two separate jobs appear on the PR: `Frontend (test, typecheck, build)` and `Apps Script (test, typecheck)`. Frontend runs `npm ci` → `npm test` → `npx tsc --noEmit` → `npm run build`; Apps Script runs `npm ci` → `npm test` → `npm run typecheck`. Both concluded SUCCESS.

#### AC3: A failing test turns the check red — PASS (empirically, not inferred)
Pushed commit `db54fec` with a deliberate `expect(1).toBe(2)` in `apps-script/tests/rules.test.ts`. Result: `Apps Script (test, typecheck): COMPLETED FAILURE` while `Frontend: COMPLETED SUCCESS` — which also demonstrates AC2's attribution requirement, since the red check named which side broke. Reverted in `493f5a3`; CI returned to green on both jobs. `git diff main --stat` on the branch head shows only the 3 intended files, so the probe left no residue.

#### AC4: A bad merge to main is still visible — PASS (config-level)
`on.push.branches: [main]` is present with no path filter. This cannot be exercised before merge by definition; it will be observable on the merge commit itself. Verified by reading the workflow, and noted as such rather than claimed as an executed test.

#### AC5: apps-script typecheck covers the test files — PASS
Before: `npx tsc --noEmit -p apps-script` → `error TS18003: No inputs were found`. After widening `include` to `["src/**/*.ts", "tests/**/*.ts", "vitest.config.ts"]`: exit 0. Negative check — appending `const __ciProbe: number = "not a number";` to `tests/rules.test.ts` produced `tests/rules.test.ts(222,7): error TS2322` and exit 2, confirming the test files are genuinely covered now. Probe reverted.

#### AC6: Deployment is unaffected — PASS
`git diff main --stat` confirms `.github/workflows/deploy.yml` is untouched. The new workflow uses a distinct `concurrency` group (`ci-*`) so it cannot cancel the Pages deploy's `pages` group, and takes `permissions: contents: read` only — it has no `pages`/`id-token` write, so it cannot interfere with deployment.

### Observations
- **Mobile (375px) / dark theme / console:** N/A. This issue changes only CI configuration and TypeScript project setup; there is no user-facing surface to exercise in demo mode. Demo mode was not run, and no UI criterion is being claimed as verified.
- **Rules sync:** not applicable — no business rules or types touched (`rules.ts`/`rules.js`, `types.ts`/`types.js` all unmodified).
- `frontend`'s `npm run build` already runs `tsc --noEmit` internally, so the typecheck is nominally duplicated; it is kept as its own step so a type error is attributable on its own line rather than buried in a build failure. Costs a few seconds.
- The CI workflow is not covered by a unit test asserting its triggers. A live green/red check is stronger evidence than a YAML parse test, and the run above provides it.

### Verdict: PASS
